### ISSUE TITLE
Not quite drop-in replacement

### ISSUE THREAD

**Issue by dmyyy** [brurucy/indexset#1]
I ran into several issues when trying to replace BTree usage in https://github.com/indradb/indradb with this library

Seems like the issues are as follows
- Serialize, Deserialize not implemented
- No entry method

Relevant errors
`
312 |         self.internal.vertices.entry(vertex.id).or_insert_with(|| {
    |                                ^^^^^ method not found in BTreeMap<Uuid, Identifier>
`

**Comment by brurucy** [comment]
Thank you a lot for trying to integrate it with indradb.

I will attempt to implement the `entry` API in a way that `indradb` will compile.

Do you happen to have a benchmark suite somewhere? I could not find looking at the code.

**Comment by brurucy** [comment]
Hey there @dmyyy, I have successfully compiled `indradb` with `indexset` 0.2.0 now.

**Comment by dmyyy** [comment]
Thank you! A little bit busy now but I'll play around with it and try to make a pr
