### ISSUE TITLE
lower_bound in BTreeMap

### ISSUE THREAD

**Issue by KiaShakiba** [brurucy/indexset#2]
Any plans to support the `lower_bound` function in BTreeMap?

**Comment by KiaShakiba** [comment]
Great! Thanks!

**Comment by brurucy** [comment]
I saw that https://github.com/rust-lang/rust/issues/107540 is still **very much** in discussion, so it's quite unlikely that it will come out anytime soon.

Nonetheless, the design of `Cursor`, not `mut`, seems to be fixed, so I will only release `lower_bound` in `0.3.0`, to avoid a major release.
