### ISSUE TITLE
range behavior is inconsistent with std.

### ISSUE THREAD

**Issue by kekeimiku** [brurucy/indexset#4]
[README.md](https://github.com/brurucy/indexset/blob/master/README.md) it is(mostly) a drop-in replacement for the stdlib BTree.

indexset::BTreeMap:
```rust
use indexset::BTreeMap;
use std::ops::Bound::Included;

fn main() {
    let mut map = BTreeMap::new();
    for i in 1..10 {
        map.insert(i, i.to_string());
    }
    let count = map.range((Included(5), Included(11))).count();
    println!("{count}")
}
```
result:
```
panic
indexset/src/lib.rs:1322:39:
index out of bounds: the len is 1 but the index is 1
```

std::collections::BTreeMap:
```rust
use std::collections::BTreeMap;
use std::ops::Bound::Included;

fn main() {
    let mut map = BTreeMap::new();
    for i in 1..10 {
        map.insert(i, i.to_string());
    }
    let count = map.range((Included(5), Included(11))).count();
    println!("{count}")
}
```
result:
```
5
```

**Comment by Cydhra** [comment]
The problem is likely `fn range_idx` (I hope this behavior isn't implemented in several places).
It will access the BTree leaves of the range indices, but if the range indices are out of bounds (like 11 in your example) it will try to access a leave that doesn't exist:

```rs
let (
    (global_front_idx, front_node_idx, front_start_idx),
    (global_back_idx, back_node_idx, back_start_idx),
) = self.resolve_range(range);

// Not the best way...advancing iterators until the correct starting point
let mut front_iter = self.inner[front_node_idx].inner.iter();
for _ in 0..front_start_idx {
    front_iter.next();
}

// ....
````

**Comment by brurucy** [comment]
Oof!

Will look into that ASAP. @Cydhra if your PR comes first I'll respond to it ASAP.

**Comment by Cydhra** [comment]
I think I'll PR this one first, because the test case I suggested in #5 doesn't go green when I fix stuff, because it will inevitably trigger this bug here after I fixed the rest, since the Range ``0..0`` will be out of bounds for an empty set.
